// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxyexridozhsofyukhvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eWV4cmlkb3poc29meXVraHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjIzOTQsImV4cCI6MjA2MjMzODM5NH0.uFe1uPH-1HifGelPEvtMmD_d1pITYfHpSSKc_LEDNTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);